on:
  push:
    branches:
      - main

concurrency:
  group: azure-deployment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and deploy
        run: echo 'Deploying...'